### PR TITLE
[WIP] Add LiveReload

### PR DESCRIPTION
**Pull request by amyrlam**

### CODE REVIEW

**Comment by amyrlam** [comment]
livereload

@yangshun This attempt at LiveReload with the [Chrome extension](https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei?hl=en) works on a hard refresh. 

It's definitely better than killing `yarn start` every time.

But the extension made it sound like it would work on file save? Any ideas?

**Comment by yangshun** [comment]
This is getting close but not quite there yet. What LiveReload does is to refresh the browser automatically when the code changes. You shouldn't need to do a browser refresh, it should refresh automatically. I think what you recorded in the gif currently exists in Docusaurus.

I think the live reload task wasn't clear at the start, my bad. I'll explain in-depth here.

**Current Behavior:** When a user edits any documentation/blog file, they have to refresh the browser to see the updated changes. I believe they currently do not have to kill the server and do `yarn start` again.

**Ideal Behavior:** When a user edits any documentation/blog file, the server tells the browser to refresh automatically - the user does not have to trigger this behavior themself.

Also, it wouldn't be reasonable to expect all the users to have the LiveReload Chrome extension installed. On a high level, what the LiveReload extension does is to inject a script tag into the page. To fully add LiveReload functionality, modifications will have to be made to both client side and server side. Your PR currently handles the server side, what it's missing is the client side addition 👍

Refer to https://github.com/livereload/livereload-js for how to add code on the client side.

**Comment by amyrlam** [comment]
Ok, yes I see what you're saying. If I edit `getting-started-preparation.md`, and do a hard refresh on http://localhost:3000/docs/en/next/site-preparation.html, I see the changes _without_ the LiveReload extension.

Before, I would not see the edits on a hard refresh unless I killed `yarn start`. 

(I had a problem with LiveReload this week at work, which I think was related to my problem with LiveReload in Docusaurus before. Basically, before LiveReload wasn't working on my machine anywhere.)

**Comment by yangshun** [comment]
> Before, I would not see the edits on a hard refresh unless I killed yarn start.

Are you sure about that? I think it was always working that way for doc changes. I might be wrong though.

**Comment by amyrlam** [comment]
I think that it might have been a system-wide problem on my computer, since it was also happening to me on other repos, where LiveReload functionality is built in. But I fixed that on my machine on Friday at work by passing `--live-reload-port=9999`. If it happens again I'll take a gif...

**Comment by amyrlam** [comment]
will open new PR on docusaurus repo shortly.

**Pull request closed without merging**
